alias: NFC - Abrir portão e Notificar Usuário
description: Executa trava do portão ao ler TAG NFC e envia notificação
triggers:
  - tag_id: "id_da_sua_tag_nfc_passiva"
    trigger: tag
actions:
  - action: switch.turn_on
    target:
      entity_id: switch.porteiro_esp32_zero_trava_do_portao
    data: {}
  - parallel:
      - action: camera.snapshot
        target:
          entity_id: camera.camera_porteiro
        data:
          filename: /config/www/porteiro_last.jpg
  - delay: "00:00:01"
  - action: notify.mobile_seu_celular
    data:
      title: Abertura do Portão
      message: 🚪 Portão aberto por TAG NFC.
      data:
        image: /local/porteiro_last.jpg?v={{ as_timestamp(now()) }}
        clickAction: /local/porteiro_last.jpg?v={{ as_timestamp(now()) }}
        importance: high
        priority: high
variables:
  ts: "{{ as_timestamp(now()) }}"
mode: single
