alias: Porteiro - Direcionar Notificação de Entrega
description: ""
triggers:
  - entity_id: sensor.gemini_ultimo_status_entrega
    trigger: state
conditions:
  - condition: template
    value_template: "{{ states('sensor.gemini_ultimo_status_entrega') != 'unknown' }}"
actions:
  - data:
      nome_morador: "{{ states('sensor.gemini_ultimo_status_entrega') }}"
      celular_destinatario: >
        {% set morador = states('sensor.gemini_ultimo_status_entrega') | lower
        %} {% if 'jose' in morador or 'epelido1' in morador or 'apelido2' in
        morador %}
          mobile_celular_jose
        {% elif 'maria' in morador or 'apelido1' in morador or 'apelido2' in morador
        %}
          mobile_celular_maria
        {% else %}
          # Se ele não tiver certeza, manda para o seu celular por segurança
          mobile_celular_jose
        {% endif %}
    action: script.notificacao_entrega_no_portao
