alias: "Automação: Ativar Monstrão por Presença com Cooldown"
description: >-
  Dispara reconhecimento facial apenas quando alguém fica 8s parado, aplica
  cooldown de 2 minutos e evita disparo se o portão foi aberto recentemente.
triggers:
  - entity_id: binary_sensor.porteiro_monstrinho_radar_porteiro
    to: "on"
    for:
      seconds: 8
    trigger: state
conditions:
  - condition: state
    entity_id: script.processar_reconhecimento_facial_por_movimento
    state: "off"
  - condition: state
    entity_id: timer.cooldown_porteiro
    state: idle
  - condition: state
    entity_id: switch.porteiro_esp32_zero_trava_do_portao
    state: "off"
    for:
      seconds: 15
actions:
  - action: script.turn_on
    target:
      entity_id:
        - script.processar_reconhecimento_facial_por_movimento
    data: {}
  - action: timer.start
    target:
      entity_id: timer.cooldown_porteiro
mode: single
