alias: Notificação de visita
description: Notificação com foto atualizada ao tocar o porteiro
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.porteiro_esp32_zero_botao_do_porteiro
    to: "on"
actions:
  - action: camera.snapshot
    data:
      filename: /config/www/porteiro_last.jpg
    target:
      entity_id: camera.camera_porteiro
  - delay: "00:00:01"
  - action: notify.mobile_seu_celular
    data:
      title: Visita no portão
      message: 🚨 Detecção de visita no portão
      data:
        image: /local/porteiro_last.jpg?v={{ as_timestamp(now()) }}
        clickAction: /local/porteiro_last.jpg?v={{ as_timestamp(now()) }}
        importance: high
        priority: high
        actions:
          - action: ABRIR_PORTAO_MONSTRAO
            title: 🔓 ABRIR PORTÃO
          - action: IGNORAR
            title: Ignorar
variables:
  ts: "{{ as_timestamp(now()) }}"
mode: single
